"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dotenv_1 = __importDefault(require("dotenv"));
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const db_1 = __importDefault(require("./config/db"));
const globalErrorHandler_1 = require("./middlewares/globalErrorHandler");
const authRoute_1 = __importDefault(require("./routes/authRoute"));
const storyRoutes_1 = __importDefault(require("./routes/storyRoutes"));
const saveRoutes_1 = __importDefault(require("./routes/saveRoutes"));
const uploadRoutes_1 = __importDefault(require("./routes/uploadRoutes"));
const userRoutes_1 = __importDefault(require("./routes/userRoutes"));
const topicsRoutes_1 = __importDefault(require("./routes/topicsRoutes"));
const commentRoutes_1 = __importDefault(require("./routes/commentRoutes"));
const followTopicsRoutes_1 = __importDefault(require("./routes/followTopicsRoutes"));
const followPeopleRoutes_1 = __importDefault(require("./routes/followPeopleRoutes"));
const profileRoute_1 = __importDefault(require("./routes/profileRoute"));
dotenv_1.default.config();
const app = (0, express_1.default)();
(0, db_1.default)();
app.use((0, cors_1.default)({ origin: process.env.CLIENT_URL, credentials: true }));
app.use(globalErrorHandler_1.globalErrorHandler);
app.use(express_1.default.json());
app.use("/api/auth", authRoute_1.default);
app.use("/api", userRoutes_1.default);
app.use("/api", storyRoutes_1.default, saveRoutes_1.default, uploadRoutes_1.default, topicsRoutes_1.default, commentRoutes_1.default, followTopicsRoutes_1.default, followPeopleRoutes_1.default, profileRoute_1.default);
const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
